//! Unicode property table generator.
//!
//! Parses the UCD data files checked into `ucd/` (pinned Unicode version —
//! see the generated header) and writes `src/unicode/tables.rs`: property
//! enums + sorted, merged `(start, end, value)` range tables for binary
//! search at runtime. This is the project's "no unicode-* crates" answer:
//! the data lives in-repo and regenerating is one command.
//!
//! Run: `cargo run --example gen_unicode` (from `crates/lntrn-text/`), then rebuild.

use std::collections::BTreeSet;
use std::fmt::Write as _;

const UNICODE_VERSION: &str = "17.0.0";

fn main() {
    let root = env!("CARGO_MANIFEST_DIR");
    let read = |name: &str| {
        std::fs::read_to_string(format!("{root}/ucd/{name}"))
            .unwrap_or_else(|e| panic!("reading ucd/{name}: {e}"))
    };

    let grapheme = merge(parse(&read("GraphemeBreakProperty.txt")));
    let ext_pict: Vec<(u32, u32, String)> = merge(
        parse(&read("emoji-data.txt"))
            .into_iter()
            .filter(|(_, _, v)| v == "Extended_Pictographic")
            .collect(),
    );
    let scripts = merge(parse(&read("Scripts.txt")));
    let line_break = merge(parse(&read("LineBreak.txt")));

    // BidiClass: real entries overlaid on the file's `@missing` default
    // ranges (unassigned code points in e.g. the Arabic blocks default to
    // AL/R — required for correct paragraph direction detection).
    let bidi_src = read("DerivedBidiClass.txt");
    let bidi = merge(layer(&parse_missing(&bidi_src), &merge(parse(&bidi_src))));
    let mirror = parse_pairs(&read("BidiMirroring.txt"));
    let joining = merge(parse_arabic_shaping(&read("ArabicShaping.txt")));

    let mut out = String::new();
    let _ = writeln!(
        out,
        "//! AUTO-GENERATED by `examples/gen_unicode.rs` from `ucd/` \
         (Unicode {UNICODE_VERSION}).\n\
         //! Do not edit by hand; regenerate with `cargo run --example gen_unicode`.\n\
         //! (Generated data tables — exempt from the file-length guideline.)\n\
         #![allow(clippy::all)]\n"
    );

    emit_enum(&mut out, "GraphemeBreak", "Other", &grapheme);
    emit_table(&mut out, "GRAPHEME_BREAK", "GraphemeBreak", &grapheme);
    emit_pairs(&mut out, "EXTENDED_PICTOGRAPHIC", &ext_pict);
    emit_enum(&mut out, "Script", "Unknown", &scripts);
    emit_table(&mut out, "SCRIPTS", "Script", &scripts);
    emit_enum(&mut out, "LineBreakClass", "XX", &line_break);
    emit_table(&mut out, "LINE_BREAK", "LineBreakClass", &line_break);
    emit_enum(&mut out, "BidiClass", "L", &bidi);
    emit_table(&mut out, "BIDI_CLASS", "BidiClass", &bidi);
    emit_pairs(&mut out, "MIRROR_PAIRS", &mirror);
    emit_enum(&mut out, "JoiningType", "U", &joining);
    emit_table(&mut out, "JOINING_TYPE", "JoiningType", &joining);

    let path = format!("{root}/src/unicode/tables.rs");
    std::fs::write(&path, out).expect("writing tables.rs");
    println!(
        "wrote {path}: {} grapheme + {} ext-pict + {} script + {} line-break + \
         {} bidi + {} mirror + {} joining ranges",
        grapheme.len(),
        ext_pict.len(),
        scripts.len(),
        line_break.len(),
        bidi.len(),
        mirror.len(),
        joining.len()
    );
}

/// Parse `# @missing: XXXX..YYYY; Long_Name` default-range annotations,
/// mapping the long value names to the short codes the data lines use.
fn parse_missing(text: &str) -> Vec<(u32, u32, String)> {
    text.lines()
        .filter_map(|line| {
            let rest = line.strip_prefix("# @missing:")?.trim();
            let (range, value) = rest.split_once(';')?;
            let (a, b) = range.trim().split_once("..")?;
            let short = match value.trim() {
                "Left_To_Right" => "L",
                "Right_To_Left" => "R",
                "Arabic_Letter" => "AL",
                "European_Terminator" => "ET",
                other => other,
            };
            Some((
                u32::from_str_radix(a.trim(), 16).ok()?,
                u32::from_str_radix(b.trim(), 16).ok()?,
                short.to_string(),
            ))
        })
        .collect()
}

/// Overlay `real` entries on `base` default ranges: gaps in the overlay are
/// filled from the base (skipping the global L default — that's the lookup
/// fallback).
fn layer(base: &[(u32, u32, String)], real: &[(u32, u32, String)]) -> Vec<(u32, u32, String)> {
    let mut out = real.to_vec();
    for (bs, be, bv) in base {
        if bv == "L" {
            continue;
        }
        let mut cursor = *bs;
        for (os, oe, _) in real.iter().filter(|(os, oe, _)| oe >= bs && os <= be) {
            if *os > cursor {
                out.push((cursor, os - 1, bv.clone()));
            }
            cursor = cursor.max(oe.saturating_add(1));
        }
        if cursor <= *be {
            out.push((cursor, *be, bv.clone()));
        }
    }
    out.sort_by_key(|r| r.0);
    out
}

/// `BidiMirroring.txt`: `XXXX; YYYY # ...` — char → its mirrored partner.
fn parse_pairs(text: &str) -> Vec<(u32, u32, String)> {
    let mut out: Vec<(u32, u32, String)> = text
        .lines()
        .filter_map(|line| {
            let line = line.split('#').next().unwrap_or("").trim();
            let (a, b) = line.split_once(';')?;
            Some((
                u32::from_str_radix(a.trim(), 16).ok()?,
                u32::from_str_radix(b.trim(), 16).ok()?,
                String::new(),
            ))
        })
        .collect();
    out.sort_by_key(|r| r.0);
    out
}

/// `ArabicShaping.txt`: `code; name; joining type; joining group` — single
/// code points, third field is the type (U/C/D/L/R/T).
fn parse_arabic_shaping(text: &str) -> Vec<(u32, u32, String)> {
    text.lines()
        .filter_map(|line| {
            let line = line.split('#').next().unwrap_or("").trim();
            if line.is_empty() {
                return None;
            }
            let mut fields = line.split(';');
            let code = u32::from_str_radix(fields.next()?.trim(), 16).ok()?;
            let _name = fields.next()?;
            let ty = fields.next()?.trim().to_string();
            Some((code, code, ty))
        })
        .collect()
}

/// Parse the standard UCD line format: `XXXX[..YYYY] ; Value # comment`.
fn parse(text: &str) -> Vec<(u32, u32, String)> {
    text.lines()
        .filter_map(|line| {
            let line = line.split('#').next().unwrap_or("").trim();
            if line.is_empty() {
                return None;
            }
            let (range, value) = line.split_once(';')?;
            let range = range.trim();
            let (a, b) = match range.split_once("..") {
                Some((a, b)) => (a, b),
                None => (range, range),
            };
            Some((
                u32::from_str_radix(a.trim(), 16).ok()?,
                u32::from_str_radix(b.trim(), 16).ok()?,
                value
                    .trim()
                    .split(';')
                    .next()
                    .unwrap_or("")
                    .trim()
                    .to_string(),
            ))
        })
        .collect()
}

/// Sort by start and merge adjacent ranges with the same value.
fn merge(mut ranges: Vec<(u32, u32, String)>) -> Vec<(u32, u32, String)> {
    ranges.sort_by_key(|r| r.0);
    let mut out: Vec<(u32, u32, String)> = Vec::with_capacity(ranges.len());
    for (start, end, value) in ranges {
        match out.last_mut() {
            Some((_, pe, pv)) if *pv == value && start == *pe + 1 => *pe = end,
            _ => out.push((start, end, value)),
        }
    }
    out
}

/// `Regional_Indicator` → `RegionalIndicator`; UCD names are already
/// identifier-safe apart from underscores.
fn variant(name: &str) -> String {
    let mut out = String::new();
    let mut upper_next = true;
    for ch in name.chars() {
        if ch == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(ch.to_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn emit_enum(out: &mut String, name: &str, default: &str, ranges: &[(u32, u32, String)]) {
    let mut variants: BTreeSet<String> = ranges.iter().map(|(_, _, v)| variant(v)).collect();
    variants.insert(default.to_string());
    let _ = writeln!(
        out,
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub enum {name} {{"
    );
    // Default variant first so `#[default]`-style reasoning is easy to eyeball.
    let _ = writeln!(out, "    {default},");
    for v in variants.iter().filter(|v| *v != default) {
        let _ = writeln!(out, "    {v},");
    }
    let _ = writeln!(out, "}}\n");
}

fn emit_table(out: &mut String, name: &str, ty: &str, ranges: &[(u32, u32, String)]) {
    let _ = writeln!(out, "pub static {name}: &[(u32, u32, {ty})] = &[");
    for (start, end, value) in ranges {
        let _ = writeln!(out, "    ({start:#x}, {end:#x}, {ty}::{}),", variant(value));
    }
    let _ = writeln!(out, "];\n");
}

fn emit_pairs(out: &mut String, name: &str, ranges: &[(u32, u32, String)]) {
    let _ = writeln!(out, "pub static {name}: &[(u32, u32)] = &[");
    for (start, end, _) in ranges {
        let _ = writeln!(out, "    ({start:#x}, {end:#x}),");
    }
    let _ = writeln!(out, "];\n");
}
